"""Add user_id to pill_reminder

Revision ID: 459b49821065
Revises: 572ebd88f0ff
Create Date: 2025-01-01 00:17:50.871174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '459b49821065'
down_revision = '572ebd88f0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_sugar', sa.Float(), nullable=True),
    sa.Column('blood_sugar_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_pressure_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('heart_rate_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('body_temperature', sa.Float(), nullable=True),
    sa.Column('body_temperature_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),  # Added length
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('height_unit', sa.String(255), nullable=False),  # Added length
    sa.Column('gender', sa.String(255), nullable=True),  # Added length
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_information_id', sa.Integer(), nullable=True),
    sa.Column('physical_attributes_id', sa.Integer(), nullable=True),
    sa.Column('health_metrics_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['health_metrics_id'], ['health_metrics.id'], ),
    sa.ForeignKeyConstraint(['personal_information_id'], ['personal_information.id'], ),
    sa.ForeignKeyConstraint(['physical_attributes_id'], ['physical_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pill_reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pill_reminder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('dashboard')
    op.drop_table('physical_attributes')
    op.drop_table('personal_information')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
