"""empty message

Revision ID: df68bc956c38
Revises: 
Create Date: 2024-12-24 18:39:26.343873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df68bc956c38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pill_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('pill_time', sa.Time(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('missed_pills', sa.Integer(), nullable=True),
    sa.Column('taken_pills', sa.Integer(), nullable=True),
    sa.Column('email_notification', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pill_reminder')
    # ### end Alembic commands ###
